"""Add crown_earned to LessonAttempt

Revision ID: 1134fcb0aa41
Revises: 364dce73abf6
Create Date: 2026-08-13 14:11:12.118149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1134fcb0aa41'
down_revision: Union[str, Sequence[str], None] = '364dce73abf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crown_earned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_attempts', schema=None) as batch_op:
        batch_op.drop_column('crown_earned')

    # ### end Alembic commands ###
