"""add idx_unique_correct_attempt

Revision ID: 364dce73abf6
Revises: b429ad793460
Create Date: 2026-08-13 11:37:42.095460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364dce73abf6'
down_revision: Union[str, Sequence[str], None] = 'b429ad793460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_attempts', schema=None) as batch_op:
        batch_op.create_index('idx_unique_correct_attempt', ['lesson_attempt_id', 'exercise_id'], unique=True, sqlite_where=sa.text('is_correct = 1'), postgresql_where=sa.text('is_correct = 1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_attempts', schema=None) as batch_op:
        batch_op.drop_index('idx_unique_correct_attempt', sqlite_where=sa.text('is_correct = 1'), postgresql_where=sa.text('is_correct = 1'))

    # ### end Alembic commands ###
