"""Add check constraints

Revision ID: b429ad793460
Revises: 05a520883702
Create Date: 2026-08-13 10:47:05.655166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b429ad793460'
down_revision: Union[str, Sequence[str], None] = '05a520883702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_attempts', schema=None) as batch_op:
        batch_op.create_check_constraint('chk_current_exercise_index_positive', 'current_exercise_index >= 0')
        batch_op.create_check_constraint('chk_hearts_lost_positive', 'hearts_lost >= 0')
        batch_op.create_check_constraint('chk_xp_awarded_positive', 'xp_awarded >= 0 OR xp_awarded IS NULL')

    with op.batch_alter_table('skill_progress', schema=None) as batch_op:
        batch_op.create_check_constraint('chk_crown_level_positive', 'crown_level >= 0')
        batch_op.create_check_constraint('chk_lessons_completed_positive', 'lessons_completed_in_level >= 0')
        batch_op.create_check_constraint('chk_xp_earned_positive', 'xp_earned >= 0')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_progress', schema=None) as batch_op:
        batch_op.drop_constraint('chk_xp_earned_positive', type_='check')
        batch_op.drop_constraint('chk_lessons_completed_positive', type_='check')
        batch_op.drop_constraint('chk_crown_level_positive', type_='check')

    with op.batch_alter_table('lesson_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('chk_xp_awarded_positive', type_='check')
        batch_op.drop_constraint('chk_hearts_lost_positive', type_='check')
        batch_op.drop_constraint('chk_current_exercise_index_positive', type_='check')

    # ### end Alembic commands ###
